# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1esZDSePB6T5QkPWE6EDFnWxbtszz-mQ-
"""

name = input("Type name here:")
print("Hello", name)

num1 = float(2.7)
num2 = float(2.4)
print(num1 + num2)